app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from inicio import views
from django.conf.urls import handler404
from inicio.views import mi_error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.InicioView.as_view(), name='index'),
    #vistas en desarollo
    #path('contacto', views.ContactoView.as_view(), name='contacto'),
    #path('equipo', views.EquipoTrabajoView.as_view(), name='equipo-trabajo'),
    #path('municipios-socios', views.MunicipiosSociosView.as_view(), name='municipios-socios'),
    #path('sobre-nosotros', views.SobreNosotrosView.as_view(), name='sobre-nosotros'),
    #gestion documentaria ruta que se debe proteger

    path('', include('ejeproyectos.urls')),
    path('', include('infopublic.urls')),
    path('', include('baseconocimiento.urls')),
    path('', include('publicaciones.urls')),
    path('', include('juntadirectiva.urls')),
    path('', include('inicio.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = mi_error_404 

app/juntadirectiva/urls.py
from . import views
from .views import *
from django.urls import path, include

urlpatterns = [

    path('junta-directiva', views.JuntaDirectivaView, name='junta-directiva'),

]

app/juntadirectiva/models.py
from django.db import models

#Junta directiva
class JuntaDirectiva(models.Model):
    nombre_representante = models.CharField(max_length=200) 
    fotografia = models.ImageField(upload_to='juntad')
    DIRECTIVA = [
        (0, ""),
        (1, "PRESIDENTE"),
        (2, "VICE PRESIDENTE"),
        (3, "SECRETARIA"),
        (4, "TESORERA"),
        (5, "VOCAL 1"),
        (6, "VOCAL 2"),
        (7, "VOCAL 3"),
    ]
    electivo = models.DateField(auto_now_add=False)
    puesto = models.IntegerField(choices=DIRECTIVA, null=False, blank=False, default=0)
    STATUS = [
        (0, "Publicado"),
        (1, "Ocultar"),
    ]
    status = models.IntegerField(choices=STATUS, default=0)
    fecha_publicacion =  models.DateTimeField(auto_now_add=True) 

    class Meta:
        verbose_name = "Junta Directiva"
  

app/juntadirectiva/views.py
from django.shortcuts import render
from django.views import generic
from .models import JuntaDirectiva
from django.views import generic
from django.core.paginator import Paginator
# Create your views here.


def JuntaDirectivaView(request):
    directiva = JuntaDirectiva.objects.all()
    paginator = Paginator(directiva,6) 
    page_number=request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'junta_directiva/juntadirectiva.html', context={'directiva': directiva, 'directiva': page_obj} )

app/templates/junta_directiva/juntadirectiva.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="main">
    <div class="page-header page-header-xs" data-parallax="true" style="background-image:  url('{% static "img/blubac.jpeg"%}')">
        <div class="filter"></div>
        <div class="container">
            <div class="motto text-center">
            </br>
              <h2>Junta Directiva</h2>
            
            </div>
          </div>
      </div>
</div>
<div class="section profile-content">
  <div class="container">
    <div class="owner">
      <br/>
      <br/>
      <br/>
      <div class="name">
        <h4 class="title">Junta Directiva 2022-2024
        </h4>
      </div>
    </div>

    <br/>
    <div class="nav-tabs-navigation">
      <div class="nav-tabs-wrapper">
        <ul class="nav nav-tabs" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#follows" role="tab">Integrantes</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- Tab panes -->
    <div class="tab-content following">
      <div class="tab-pane active" id="follows" role="tabpanel">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <ul class="list-unstyled follows">
              <li>
                <!-- Recorrido para los demas inegrantes mostrar solo año electivo-->
                      
            {% for directiva in directiva %}

                <div class="row">
                  <div class="col-lg-4 col-md-4 col-4 ml-auto mr-auto">
                    <img src="{{ directiva.fotografia.url }}"   alt="Circle Image" class="img-circle img-no-padding img-responsive">
                  </div>
                  <div class="col-lg-7 col-md-4 col-4  ml-auto mr-auto">
                    <h6>{{ directiva.nombre_representante }}
                      <br/>
                      <small>{{ directiva.get_puesto_display|default_if_none:'' }}</small>
                    </h6>
                  </div>
                </div>
              </li>
              {% endfor %}

            </ul>
          </div>
        </div>
      </div>
      <div class="tab-pane text-center" id="following" role="tabpanel">
        <h3 class="text-muted">Not following anyone yet :(</h3>
        <button class="btn btn-warning btn-round">Find artists</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}