app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from inicio import views
from django.conf.urls import handler404
from inicio.views import mi_error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.InicioView.as_view(), name='index'),
    #vistas en desarollo
    #path('contacto', views.ContactoView.as_view(), name='contacto'),
    #path('equipo', views.EquipoTrabajoView.as_view(), name='equipo-trabajo'),
    #path('municipios-socios', views.MunicipiosSociosView.as_view(), name='municipios-socios'),
    #path('sobre-nosotros', views.SobreNosotrosView.as_view(), name='sobre-nosotros'),
    #gestion documentaria ruta que se debe proteger

    path('', include('ejeproyectos.urls')),
    path('', include('infopublic.urls')),
    path('', include('baseconocimiento.urls')),
    path('', include('publicaciones.urls')),
    path('', include('juntadirectiva.urls')),
    path('', include('inicio.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = mi_error_404 

app/ejeproyectos/models.py
from django.db import models

# Create your models here.
class Eje(models.Model):
    nombre_eje = models.CharField(max_length=200) 

    def __str__(self):
        return self.nombre_eje    
    class Meta:
        verbose_name = "Ejes" 
        verbose_name_plural = "Ejes" 

class Cooperante(models.Model):
    nombre_cooperante = models.CharField(max_length=200) 

    def __str__(self):
        return self.nombre_cooperante  
    class Meta:
        verbose_name = "Nombre del cooperante" 

class LugarEjecucion(models.Model):
    nombre_lugar = models.CharField(max_length=200) 

    def __str__(self):
        return self.nombre_lugar
    class Meta:
        verbose_name = "Lugar de ejecución"
        verbose_name_plural = "Lugar de ejecución"  

class Proyecto(models.Model):
    titulo = models.CharField(max_length=200) 
    descripcion = models.CharField(max_length=200) 
    imagen_principal = models.ImageField(upload_to='noticias_imagenes')
    eje = models.ForeignKey(Eje, on_delete= models.CASCADE,related_name='eje', null=False, blank=False)
    cooperante = models.ForeignKey(Cooperante, on_delete= models.CASCADE,related_name='coperante', null=False, blank=False)
    lugar_ejecucion  = models.ForeignKey(LugarEjecucion, on_delete= models.CASCADE,related_name='ejecucion', null=False, blank=False)
    AVANCESPROYECTO = [
        (0, ""),
        (1, "Iniciado"),
        (2, "En progreso"),
        (3, "Finalizado"),
    ]
    avances_proyecto = models.IntegerField(choices=AVANCESPROYECTO, default=0)
    STATUS = [
        (0, "Publicado"),
        (1, "Ocultar"),
    ]
    status = models.IntegerField(choices=STATUS, default=0)
    fecha_publicacion =  models.DateTimeField(auto_now_add=True) 
    class Meta:
        ordering = ['-fecha_publicacion']

    def __str__(self):
        return self.titulo
    class Meta:
        verbose_name = "Publicación de proyectos"
  
class PostGaleryImage(models.Model):
    post = models.ForeignKey(Proyecto, default=None, on_delete=models.CASCADE)
    imagenes= models.FileField(upload_to = 'proyectos/')
    class Meta:    
        verbose_name = "Fotografias"

app/templates/proyectos/proyectos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="main">
  <div class="page-header page-header-xs" data-parallax="true" style="background-image:  url('{% static "img/blubac.jpeg"%}')">
    <div class="filter"></div>
    <div class="container">
        <div class="motto text-center">
        </br>
          <h2>Proyectos</h2>
        </div>
      </div>
  </div>
  <div class="section profile-content">
    <div class="container">
      <div class="owner">
        <br />      
        <br />
        <div class="name">
          <h6></h6>
        </div>
      </div>
      <div class="section">
        <div class="container">
                    <h3 class="card-title" style="color: #00000; font-weight: bold; font-size: 25px;">Proyectos</h3>
          <div class="row">
            <div class="col-md-12  d-flex align-items-stretch">
                {% for proyectos in proyectos %}
              <div class="card col-lg-4 ">
                  <div class="card-body">
                      <img class="card-img-top" src="{{ proyectos.imagen_principal.url }}"  alt="Card image cap">
                      </br>
                      </br>
                      <p style="color: #3d3d3d; font-weight: Bold; font-size: 18px;">{{ proyectos.titulo|truncatewords:"10"|linebreaks }}</p>
                      <p class="card-text text-justify" style="color: #000000; font-weight: regular; font-size:15;">{{ proyectos.descripcion|truncatewords:"8"|linebreaks}}</p>
                      <br>
                      <p style="text-align: left;"><strong>Categoria: </strong>{{ proyectos.eje}}</p>
                      <p style="text-align: left;"><strong>Cooperante: </strong>{{ proyectos.cooperante}}</p>
                      <p style="text-align: left;"><strong>Fase del proyecto: </strong>{{ proyectos.get_avances_proyecto_display|default_if_none:''}}</p>
                      <a href="{{ proyectos.pk}}"class="btn btn-outline-default btn-round pull-right">Leer más<i class="fa fa-chevron-right"></i></a>
                  </div>
              </div>

              {% endfor %}
            </div>

          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
    <!--Pagination-->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if noticia.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ noticia.previous_page_number }}">Anterior</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
          </li>
        {% endif %}
        {% for i in noticia.paginator.page_range %}
          {% if noticia.number == i %}
            <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if noticia.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ noticia.next_page_number }}">Siguiente</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Siguiente</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <!--end of Pagination-->
{% endblock content %}